c/identity server:
  - changed-files:
      - any-glob-to-any-file:
          - pkg/identityserver/*
          - pkg/identityserver/**/*
          - pkg/account/*
          - pkg/account/**/*
          - pkg/oauth/*
          - pkg/oauth/**/*

c/gateway server:
  - changed-files:
      - any-glob-to-any-file:
          - pkg/gatewayserver/*
          - pkg/gatewayserver/**/*
          - pkg/basicstation/*

c/gateway conf server:
  - changed-files:
      - any-glob-to-any-file:
          - pkg/gatewayconfigurationserver/*
          - pkg/gatewayconfigurationserver/**/*
          - pkg/basicstation/*
          - pkg/basicstation/cups/*
          - pkg/pfconfig/*
          - pkg/pfconfig/**/*

c/network server:
  - changed-files:
      - any-glob-to-any-file:
          - pkg/networkserver/*
          - pkg/networkserver/**/*

c/device converter:
  - changed-files:
      - any-glob-to-any-file:
          - pkg/devicetemplateconverter/*
          - pkg/devicetemplates/*

c/application server:
  - changed-files:
      - any-glob-to-any-file:
          - pkg/applicationserver/*
          - pkg/applicationserver/**/*
          - pkg/messageprocessors/*
          - pkg/messageprocessors/**/*
          - pkg/scripting/*
          - pkg/scripting/**/*

c/join server:
  - changed-files:
      - any-glob-to-any-file:
          - pkg/joinserver/*
          - pkg/joinserver/**/*

c/console:
  - changed-files:
      - any-glob-to-any-file:
          - pkg/console/*
          - pkg/console/**/*

c/packet broker agent:
  - changed-files:
      - any-glob-to-any-file:
          - pkg/packetbrokeragent/*
          - pkg/packetbrokeragent/**/*

compat/api:
  - changed-files:
      - any-glob-to-any-file:
          - api/*.proto

compat/config:
  - changed-files:
      - any-glob-to-any-file:
          - cmd/**/config.go
          - cmd/**/config.*.go
          - pkg/**/config.go
          - pkg/**/config.*.go
          - pkg/config/*.go
          - pkg/config/**/*.go

compat/db:
  - changed-files:
      - any-glob-to-any-file:
          - pkg/identityserver/store/*.go
          - pkg/identityserver/store/**/*.go
          - pkg/identityserver/bunstore/*.go
          - pkg/identityserver/bunstore/**/*.go
          - pkg/**/redis/*.go
          - pkg/**/redis/**/*.go

security:
  - changed-files:
      - any-glob-to-any-file:
          - pkg/crypto/*
          - pkg/crypto/**/*

# NOTE: We're not assigning bump/minor because that is a choice for the maintainer.

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - go.mod
          - go.sum
          - yarn.lock
          - sdk/js/yarn.lock

ui/cli:
  - changed-files:
      - any-glob-to-any-file:
          - cmd/ttn-lw-cli/*
          - cmd/ttn-lw-cli/**/*

ui/web:
  - changed-files:
      - any-glob-to-any-file:
          - pkg/webui/*
          - pkg/webui/**/*
          - pkg/web/oauthclient/*

tooling:
  - changed-files:
      - any-glob-to-any-file:
          - tools/*
          - tools/**/*
